import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { MODELS } from "@/lib/config";
import { askJson } from "@/lib/anthropic";
import { currentUserId } from "@/lib/auth";
import { InventPitchesSchema } from "@/lib/schemas";
import { INVENT_PITCHES_SYSTEM } from "@/lib/prompts/cook";

export const maxDuration = 120;

/**
 * POST /api/invent — three invented dinner ideas from what's on hand.
 *
 * Deliberately does NOT see the library: this is the "make me something new"
 * half of the Pantry screen, and /api/pantry is the "what have I already saved"
 * half. The page fires both.
 *
 * Pitches only — the full recipe is generated by /api/invent/recipe for the one
 * card that gets tapped, so two thirds of these are never expanded.
 */
export async function POST(req: Request) {
  const userId = await currentUserId(req);
  if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const body = await req.json().catch(() => ({}));
  const onHand = String(body.on_hand ?? "").trim();
  if (!onHand) return NextResponse.json({ error: "Tell me what you have." }, { status: 400 });

  const cuisine = body.cuisine ? String(body.cuisine).trim() : null;
  const maxActive = Number.isFinite(Number(body.max_active_min))
    ? Number(body.max_active_min)
    : null;
  // Titles already shown this session. Without this, "give me three more"
  // returns near-duplicates of the first three and the button feels broken.
  const avoid = Array.isArray(body.avoid) ? body.avoid.map(String).slice(0, 30) : [];

  const { data: staples } = await db().from("staples").select("name").eq("user_id", userId).eq("active", true);

  const result = await askJson({
    feature: "invent",
    userId,
    model: MODELS.smart,
    system: INVENT_PITCHES_SYSTEM,
    content: JSON.stringify({
      on_hand: onHand,
      staples: (staples ?? []).map((s) => s.name),
      cuisine,
      max_active_min: maxActive,
      avoid,
    }),
    schema: InventPitchesSchema,
    maxTokens: 1500,
    // Three short pitches don't need deep deliberation, and this is the call
    // you sit and wait on — the whole screen is blocked until it lands.
    effort: "low",
  });

  return NextResponse.json(result);
}
